### ISSUE TITLE
Mark as done button bug

### ISSUE THREAD

**Issue by wertyyyy12** [wertyyyy12/The-Great-Agenda#5]
If an overdue assignment is located under an assignment that is due in >1 days, clicking the "mark as done" button for the overdue assignment casually shaves off a 0 in the year of the other assignment, making the other assignment thousands of years overdue.

**Comment by wertyyyy12** [comment]
#Seemed like an easy fix; a variable used before declaration. Seems too easy though, I'll keep this issue open just in case.

**Comment by Saragon4005** [comment]
Can you link the change?
